remove ecdhRaw usage and replace it with ecdh+custom hash function
status-im/nim-eth pull request #600
Opened 2023-04-20 08:45 UTC by jangko

2023-04-20 09:29 UTC, arnetheduck approved these changes

2023-04-20 12:37 UTC, cheatfate requested changes

2023-04-20 12:37 UTC, cheatfate commented on eth/keys.nim
> +  FullKeyLength* = 33
Where this number `33` come from?

2023-04-20 12:37 UTC, cheatfate commented on eth/keys.nim
> +func ecdhSecret*(seckey: PrivateKey, pubkey: PublicKey): SharedSecret =
This is really bad name `ecdhSecret`, it should be `ecdhSharedSecret` at least.

2023-04-20 12:37 UTC, cheatfate commented on eth/keys.nim
> +  copyMem(output, x32, 32)
Where this number `32` come from?

2023-04-21 09:09 UTC, jangko commented on eth/keys.nim
> +  FullKeyLength* = 33
fixed

2023-04-21 09:09 UTC, jangko commented on eth/keys.nim
> +func ecdhSecret*(seckey: PrivateKey, pubkey: PublicKey): SharedSecret =
changed to `ecdhSharedSecret`

2023-04-21 09:10 UTC, jangko commented on eth/keys.nim
> +  copyMem(output, x32, 32)
replaced with `KeyLength` constant

2023-04-21 09:34 UTC, cheatfate approved these changes

2023-04-21 10:06 UTC, merged