Clean up redundant code
status-im/nim-eth pull request #755
Opened 2024-10-24 11:59 UTC by chirag-parmar

2024-10-25 06:13 UTC, jangko requested changes

2024-10-25 06:13 UTC, jangko commented on eth/rlp/writer.nim
> +proc countOptionalFields(T: type): int =
if you put `debugEcho result.repr` at the end of  `genOptionalFieldsValidation` you can see the generated code. Any optional fields between mandatory fields should not produce any runtime check, although they should, but the spec for objects used in ethereum world currently don't have more than one optional fields in the middle of mandatory fields.

And your current code will produce error:
```Nim
import
  ../eth/[rlp, common]
  
type TxMock = object
  txType*        : uint64
  chainId*       : uint64
  nonce*         : uint64
  gasPrice*      : GasInt
  maxPriorityFeePerGas*: GasInt
  maxFeePerGas*  : GasInt
  gasLimit*      : GasInt
  to*            : Opt[Address]
  wow*           : Opt[uint64]
  value*         : uint64
  payload*       : seq[byte]
  maxFeePerBlobGas*: UInt256
  V*             : uint64
  R*, S*         : uint64

var tx: TxMock
let bytes = rlp.encode(tx)
```

````text
F:\projects\nim-eth\tests\test_tx.nim(21, 23) template/generic instantiation of `encode` from here
F:\projects\nim-eth\eth\rlp\writer.nim(286, 9) template/generic instantiation of `append` from here
F:\projects\nim-eth\eth\rlp\writer.nim(263, 15) template/generic instantiation of `appendImpl` from here
F:\projects\nim-eth\eth\rlp\writer.nim(251, 7) template/generic instantiation of `appendRecordType` from here
F:\projects\nim-eth\eth\rlp\writer.nim(227, 32) template/generic instantiation of `genOptionalFieldsValidation` from here
F:\projects\nim-eth\eth\rlp\writer.nim(190, 27) Error: type mismatch
Expression: isSome(obj.S)
  [1] obj.S: uint64

Expected one of (first mismatch at [position]):
[1] proc isSome[T](self: Option[T]): bool
[1] template isSome(oResultPrivate: Opt): bool
```

2024-10-25 06:27 UTC, jangko commented on eth/rlp/writer.nim
> +proc countOptionalFields(T: type): int =
if you can add '{.compileTime.}` pragma to `countOptionalFields` if it only used during compile time. It will prevent the compiler to generate runtime code for this function.

2024-10-25 08:32 UTC, arnetheduck commented on eth/rlp/writer.nim
> +proc countOptionalFields(T: type): int =
if we don't have unit tests that cover this expectation / behavior, now would be a good time to add them

2024-10-25 08:57 UTC, chirag-parmar commented on eth/rlp/writer.nim
> +proc countOptionalFields(T: type): int =
beat you to it (not officially though). Will push the test with the fixes in sometime.

2024-10-25 09:57 UTC, jangko approved these changes
unorthodox but clever.

2024-10-25 12:49 UTC, arnetheduck commented
since you're here, another "discrepancy" is that https://github.com/status-im/nim-eth/blob/master/eth/rlp/options.nim#L12 exists as a helper for `std/options` but isn't used - a similar helper exists _somewhere_ in nimbus for `Opt` and is actually used, but then in `rlp` itself there's some half-way `Opt/Option` support also, which is pretty confusing.

We're moving away from `std/options` broadly (in fact, I don't think we use them any more in rlp), so to give options a proper cleanup, this should also be attended to so that `Opt` always gets the same treatment (likely, all support for `Opt` should live in the rlp library proper but @jangko  might know better).

2024-10-25 23:58 UTC, jangko commented
`Opt/Options` often get special treatment in our encoding library. e.g. json-serialization, json-rpc, and rlp. What I mean special is not the encoding process of the field content itself, but prior to that. When `d/encoding` an object, the library need to decide what to do with the optional fields. So there are two parts regarding optional fields, (1) field content encoding, overrideable, and (2) handling optional fields of an object is coded in library. But I agree `options.nim` can be removed.

example in json-serialization:
https://github.com/status-im/nim-json-serialization/blob/6eadb6e939ffa7882ff5437033c11a9464d3385c/json_serialization/writer.nim#L91-L99

example in json-rpc:
https://github.com/status-im/nim-json-rpc/blob/98a5efba4de26ac852d0715656f6b0c52a203a75/json_rpc/private/server_handler_wrapper.nim#L138-L154

2024-10-28 05:52 UTC, chirag-parmar commented
Someone thought about this before https://github.com/status-im/nim-eth/blob/master/eth/common/base_rlp.nim#L14

2024-10-29 07:13 UTC, arnetheduck commented on eth/rlp/options.nim
> +export
exports go on top, below the import, not sure why they are here

2024-10-29 08:14 UTC, chirag-parmar commented on eth/rlp/options.nim
> +export
Good point. I'll change it.

2024-10-29 08:14 UTC, chirag-parmar commented on eth/rlp/options.nim
> +import results
Ah makes sense. I'll change it

2024-10-31 09:59 UTC, chirag-parmar commented on eth/rlp/options.nim
> +import results
https://github.com/nim-lang/Nim/issues/2819

2024-10-31 10:04 UTC, chirag-parmar commented on eth/rlp/options.nim
> +import results
@arnetheduck I have wasted too much time for this simple issue. Having the same name as the package is causing an error "cannot import itself". I tried to look for the rules of qualification and landed on the above issue. Its significantly old so maybe you know a way to qualify the package `nim-results` in an import.

2024-10-31 10:17 UTC, arnetheduck commented on eth/rlp/options.nim
> +import results
`pkg/results` and `./results`

2024-10-31 10:24 UTC, chirag-parmar commented on eth/rlp/options.nim
> +import results
🙈

2024-11-06 04:42 UTC, chirag-parmar commented
https://github.com/status-im/nimbus-eth1/actions/runs/11679712586

2024-11-06 04:46 UTC, merged